# Site settings
name: Hyder I Mohammed
email: mhyderimtiaz@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, Ruby, C++, Block Chain, Data Structures, JavaScript, Agile, Pair PHP"
skills: "Software Engineer in London, UK"
current: "Currently pursuing MSc Software Engineering"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/mhyderimtiaz/


# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: afa252
  primary-rgb: "33, 150, 243"
  secondary: 353011
  secondary-dark: fcf7d4
  section-tout: f3edc8



# Build settings
markdown: kramdown
permalink: pretty
